/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'task3_dart';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String BACK = 'assets/back.jpg';
  static const String BORING = 'assets/boring.png';
  static const String COMPANIES = 'assets/companies.png';
  static const String ELON = 'assets/elon.jpg';
  static const String HYPERLOOP = 'assets/hyperloop.png';
  static const String MUSK = 'assets/musk.jpg';
  static const String NEURALINK = 'assets/neuralink.png';
  static const String SPACEX = 'assets/spacex.png';
  static const String TESLA = 'assets/tesla.png';
  static const String TW1 = 'assets/tw1.jpg';
  static const String TW2 = 'assets/tw2.jpg';
  static const String TW3 = 'assets/tw3.png';
  static const String TW4 = 'assets/tw4.png';
  static const String TW5 = 'assets/tw5.png';
  static const String X = 'assets/x.png';
}
